on:
  workflow_dispatch:
  push:
    branches:
      - Dev
      - Prod

env:
  ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
  ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  IMAGE_TAG: ${{ github.run_number }}
  ENVNAME: ${{ github.ref_name }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  set-environment-variables:
    runs-on: ubuntu-latest
    outputs:
      ecr_repository: ${{ steps.set-vars.outputs.ecr_repository }}
      ec2_host: ${{ steps.set-vars.outputs.ec2_host }}
      s3_bucket: ${{ steps.set-vars.outputs.s3_bucket }}
    steps:
      - name: Set environment variables
        id: set-vars
        run: |
          if [ "${{ github.ref_name }}" == "Prod" ]; then
            echo "ecr_repository=${{ matrix.service }}_prod" >> $GITHUB_ENV
            echo "ec2_host=${{ vars.EC2_HOST_PROD }}" >> $GITHUB_ENV
            echo "s3_bucket=prod-xew" >> $GITHUB_ENV
          else
            echo "ecr_repository=${{ matrix.service }}_dev" >> $GITHUB_ENV
            echo "ec2_host=${{ vars.EC2_HOST_DEV }}" >> $GITHUB_ENV
            echo "s3_bucket=dev-xew" >> $GITHUB_ENV
          fi
          echo "::set-output name=ecr_repository::$ECR_REPOSITORY"
          echo "::set-output name=ec2_host::$EC2_HOST"
          echo "::set-output name=s3_bucket::$S3_BUCKET"

  build-and-push:
    runs-on: ubuntu-latest
    needs: set-environment-variables
    strategy:
      matrix:
        service: [backend_rds, backend_redis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image to ECR
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.ENVNAME }}-${{ env.IMAGE_TAG }} -f ${{ matrix.service }}/Dockerfile .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:${{ env.ENVNAME }}-${{ env.IMAGE_TAG }}


  sync-to-s3:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Sync files to S3
        run: |
          aws s3 sync frontend/ s3://$S3_BUCKET --delete

  invalidate-cache:
    runs-on: ubuntu-latest
    needs: sync-to-s3
    steps:
      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push
    strategy:
      matrix:
        service: [backend_rds, backend_redis]
    steps:
      - name: Deploy to EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ needs.set-environment-variables.outputs.ec2_host }} << EOF
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            yq e '.services.${{ matrix.service }}.image = "$ECR_REGISTRY/${{ needs.set-environment-variables.outputs.ecr_repository }}:$ENVNAME-$IMAGE_TAG"' -i docker-compose.yml
          EOF

  restart-docker-compose:
    runs-on: ubuntu-latest
    needs: deploy-to-ec2
    steps:
      - name: Restart docker-compose
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ needs.set-environment-variables.outputs.ec2_host }} << EOF
            docker-compose down
            docker-compose up -d
          EOF


# name: Deploy to ECR

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - Dev
#       - Prod

# env:
#   ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
#   ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}
#   AWS_REGION: ${{ vars.AWS_REGION }}
#   IMAGE_TAG: ${{ github.run_number }}
#   ENVNAME: ${{ github.ref_name }}

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         service: [backend_rds, backend_redis]
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Set environment variables
#       run: |
#         if [ "${{ github.ref_name }}" == "Prod" ]; then
#           ECR_REPOSITORY="${{ matrix.service }}_prod"
#           EC2_HOST=${{ vars.EC2_HOST_PROD }}
#           S3_BUCKET="prod-xew"
#         else
#           ECR_REPOSITORY="${{ matrix.service }}_dev"
#           EC2_HOST=${{ vars.EC2_HOST_DEV }}
#           S3_BUCKET="dev-xew"
#         fi
#         echo "ECR_REPOSITORY=${ECR_REPOSITORY}" >> $GITHUB_ENV
#         echo "EC2_HOST=$EC2_HOST" >> $GITHUB_ENV
#         echo "S3_BUCKET=$S3_BUCKET" >> $GITHUB_ENV

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v4
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ vars.AWS_REGION }}

#     - name: Log in to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v2

#     - name: Build and push image to ECR
#       run: |
#         docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$ENVNAME-$IMAGE_TAG -f ${{ matrix.service }}/Dockerfile .
#         docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$ENVNAME-$IMAGE_TAG

#     - name: Sync files to S3
#       run: |
#         aws s3 sync frontend/ s3://$S3_BUCKET --delete

#     - name: Invalidate CloudFront cache
#       run: |
#         aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

#     - name: Deploy to EC2
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#       run: |
#         echo "$SSH_PRIVATE_KEY" > private_key.pem
#         chmod 600 private_key.pem
#         ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_HOST << EOF
#           aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
#           yq e '.services.${{ matrix.service }}.image = "$ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$ENVNAME-$IMAGE_TAG"' -i docker-compose.yml
#         EOF

#     - name: Restart docker-compose
#       env:
#         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#       run: |
#         echo "$SSH_PRIVATE_KEY" > private_key.pem
#         chmod 600 private_key.pem
#         ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@$EC2_HOST << EOF
#           docker-compose down
#           docker-compose up -d
#         EOF